### PR TITLE
fix "QDataStream is incomplete type" compilation error

### PR DESCRIPTION
**Pull request by RushOnline**
compilation error: variable 'QDataStream plainStream' has initializer
but incomplete type

### CODE REVIEW

**Comment by RushOnline** [comment]
~~~
Qt 5.2.1
~~~

**Comment by alexeylysenko** [comment]
Thanks for your attention.
However, if this include needs only for Qt 5.2.1 (and maybe below) I'd suggest to use #ifdef to avoid including it in the latest Qt versions.

**Comment by RushOnline** [comment]
I make it work with Qt 4.8. I'll find sources and make pull request.

**Comment by alexeylysenko** [comment]
Thanks a lot, it would be great.

**Comment by alexeylysenko** [comment]
Sources have been adopted for Qt 5.12.
